"""
Single source of truth for the watchlist used by:
  - scripts/fetch_fred.py  (STOCKS)
  - scripts/competitors.py (COMPETITORS)
  - app.js                 (STOCK_META, STOCK_GROUPS, PEER_COMPETITORS)
  - Luke_wiki/wiki/news/*  (per-ticker logs)

Run scripts/gen_watchlist.py to regenerate the dependent blocks.
Each entry:
  ticker, name, sector(GICS_en), group_kr, sector_subtitle_kr, color, decimals,
  currency, business_kr, peers
"""

# Group display order (must match across all files).
# 반도체는 AI·반도체 시장지도(data/markets/ai-semiconductor.json)의 밸류체인 층과
# 1:1 로 대응하도록 4개 그룹으로 분리했다 — 시장지도 노드에서 봐야 하는 기업은
# 전부 이 watchlist 에 포함되는 것이 원칙 (지도 ↔ 개별 종목 탭 정합).
GROUPS = [
    ("빅테크 / 소프트웨어",       "글로벌 시총 상위 빅테크 + 엔터프라이즈 소프트웨어. 광고·SaaS·DB 등 다양한 수익모델."),
    ("반도체 — AI 칩 · 설계",      "GPU·커스텀 ASIC·모바일 AP·자율주행 SoC 를 설계하는 팹리스/IDM + 설계의 관문인 EDA·IP. 시장지도 'AI 컴퓨팅'과 '최종 수요(엣지)' 층."),
    ("반도체 — 메모리 (HBM·DRAM)", "HBM·DRAM·NAND 3강. AI 가속기의 1순위 병목인 HBM 적층 경쟁과 범용 메모리 슈퍼사이클."),
    ("반도체 — 파운드리 · 패키징 · 기판", "칩을 실제로 만드는 제조 기반 — 첨단 파운드리(≤3nm)·CoWoS 패키징(OSAT)·ABF 기판. 시장지도 '제조 기반' 층."),
    ("반도체 — 장비 · 소재",       "공급의 뿌리(picks & shovels) — EUV 노광·식각/증착·계측 전공정 장비 + HBM 본더·테스터·다이서 후공정 장비 + 웨이퍼/레지스트 소재."),
    ("AI 인프라 — 네트워킹 · 광 · 네오클라우드", "GPU 를 잇는 스위치·광모듈, 칩까지 전력을 전달하는 전력반도체, GPU 컴퓨트를 임대하는 네오클라우드 — 시장지도 '자본 엔진'과 부품 층의 신흥 계층."),
    ("로보틱스 / 피지컬 AI",       "휴머노이드·산업로봇·자율 시스템과 그 부품(감속기·라이다·희토류 자석·로봇 테스트). 피지컬 AI 시대의 곡괭이와 삽."),
    ("자동차 / 모빌리티",         "내연기관·EV·자율주행 전환기. 기존 완성차 + 신규 진입자 + 한국 빅2."),
    ("바이오 / 제약 / 헬스케어",  "글로벌 시총 상위 제약 + 의료기기/진단 + 의료보험. 인구 고령화 장기 수혜."),
    ("에너지 / 원자재",            "원유·가스·구리·금·산업용가스 등 실물 자산. 인플레이션·달러 약세 국면 방어주."),
    ("금융",                        "대형 은행·투자은행·결제망·지주회사. 금리·경기 사이클·신용 환경의 거울."),
    ("소비재",                      "필수 + 임의 소비재 통합. 음료·생활용품·QSR·홈임프루브먼트·스포츠웨어."),
    ("산업재 / 방산",              "건설·항공기·방산·물류·산업복합기업. 인프라·국방예산 사이클 직접 수혜."),
    ("부동산 (REITs)",             "통신탑·물류창고·데이터센터·쇼핑몰·시니어 등 다양한 자산군의 REIT."),
    ("통신 / 미디어",              "통신사·케이블·스트리밍·종합 미디어·게임. 콘텐츠·구독 경제의 중심."),
    ("유틸리티 / 전력",            "전력·가스 유틸리티. 신재생·원자력 비중 확대 + AI 데이터센터 전력수요의 수혜."),
    ("전력 인프라 (AI)",           "가스터빈·변압기·T&D·연료전지·SMR — AI 데이터센터 전력 공급망(BTM vs 그리드)의 장비·건설·차세대 발전. K-전력기기 포함."),
    ("조선 (한국)",                "K-조선 르네상스. LNG·암모니아 친환경 선박 글로벌 1위 한국 조선사들."),
]

# ============================================================================
# 종목 정의
# ============================================================================
STOCKS = [
    # ── 빅테크 / 소프트웨어 ──────────────────────────────────────────
    ("AAPL",  "Apple Inc.",                "Technology",             "빅테크 / 소프트웨어",      "기술 (하드웨어 + 서비스)",         "#9aa0a9", 2, "USD",
        "아이폰·맥 등 하드웨어와 앱스토어·iCloud 같은 서비스. 매출 절반이 아이폰. 전 세계 가장 비싼 회사 (시총 1위권)."),
    ("MSFT",  "Microsoft Corporation",     "Technology",             "빅테크 / 소프트웨어",      "기술 (소프트웨어 + 클라우드)",     "#00a4ef", 2, "USD",
        "Windows·Office 라이선스 + 클라우드 Azure. 기업 SW 시장 절대강자. OpenAI 투자로 AI 시장 선두권."),
    ("GOOGL", "Alphabet Inc.",             "Communication Services", "빅테크 / 소프트웨어",      "통신 서비스 (광고 + 클라우드)",    "#4285f4", 2, "USD",
        "구글 검색·유튜브 광고가 매출의 약 75%. 클라우드(GCP)·자율주행(Waymo)·생성형 AI(Gemini) 보유."),
    ("AMZN",  "Amazon.com Inc.",           "Consumer Discretionary", "빅테크 / 소프트웨어",      "전자상거래 + 클라우드",            "#ff9900", 2, "USD",
        "세계 최대 전자상거래. 클라우드(AWS)는 매출 비중 작지만 영업이익의 절반 이상을 책임진다."),
    ("META",  "Meta Platforms Inc.",       "Communication Services", "빅테크 / 소프트웨어",      "통신 서비스 (광고)",               "#0082fb", 2, "USD",
        "페이스북·인스타·왓츠앱 광고가 매출의 약 98%. VR(Quest)·AI 인프라에 대규모 투자 중."),
    ("ORCL",  "Oracle Corporation",        "Technology",             "빅테크 / 소프트웨어",      "기술 (데이터베이스 + 클라우드)",  "#f80000", 2, "USD",
        "기업용 데이터베이스 절대강자. 최근 AI용 GPU 클라우드(OCI)에 공격 투자."),
    ("CRM",   "Salesforce, Inc.",          "Technology",             "빅테크 / 소프트웨어",      "B2B SaaS CRM 1위",                "#00a1e0", 2, "USD",
        "기업용 SaaS·CRM(고객관리) 1위. Slack·Tableau 등 인수로 확장. 'No Software' 슬로건의 클라우드 SW 대표주."),
    ("ADBE",  "Adobe Inc.",                "Technology",             "빅테크 / 소프트웨어",      "크리에이티브 소프트웨어",          "#ff0000", 2, "USD",
        "포토샵·일러스트레이터·PDF(Acrobat) 절대 강자. 디자이너·마케터 표준 도구. 구독 전환 성공 사례."),
    ("IBM",   "International Business Machines", "Technology",       "빅테크 / 소프트웨어",      "전통 엔터프라이즈 IT",            "#0530ad", 2, "USD",
        "100년+ 역사의 엔터프라이즈 IT. 메인프레임·컨설팅(IBM Consulting)·하이브리드 클라우드(Red Hat 인수)."),
    ("PLTR",  "Palantir Technologies Inc.", "Technology",            "빅테크 / 소프트웨어",      "정부·기업 데이터 분석 SW",        "#cbd5e1", 2, "USD",
        "정부·기업 데이터 분석 SW. 미국 국방·정보기관 핵심 공급사. AI 플랫폼 AIP 로 민간 확장 중."),

    # ── 반도체 — AI 칩 · 설계 ────────────────────────────────────────
    ("NVDA",  "NVIDIA Corporation",        "Technology",             "반도체 — AI 칩 · 설계",    "AI 학습용 GPU 사실상 독점",       "#76b900", 2, "USD",
        "AI 학습용 GPU 시장 점유율 90%+. 매출 80% 이상이 데이터센터. ChatGPT 이후 AI 인프라 투자 최대 수혜주."),
    ("AMD",   "Advanced Micro Devices",    "Technology",             "반도체 — AI 칩 · 설계",    "CPU + GPU 종합 반도체",            "#ed1c24", 2, "USD",
        "CPU·GPU 동시 공급. NVIDIA 의 거의 유일한 AI 칩 경쟁자. 서버 CPU(EPYC)로 Intel 점유율 잠식 중."),
    ("INTC",  "Intel Corporation",         "Technology",             "반도체 — AI 칩 · 설계",    "x86 CPU 전통 강자 + 파운드리 도전", "#0071c5", 2, "USD",
        "x86 CPU 전통 절대강자였으나 AMD·ARM 에 밀려 점유율 하락. 파운드리(18A)·첨단 패키징으로 재기 시도. 미국 정부 CHIPS 보조금 최대 수혜자."),
    ("QCOM",  "QUALCOMM Incorporated",     "Technology",             "반도체 — AI 칩 · 설계",    "스마트폰 모뎀·SoC 프리미엄 1위",  "#3253dc", 2, "USD",
        "스마트폰 통신 모뎀·AP(Snapdragon) 프리미엄 1위. 안드로이드 진영 핵심. AI PC(Snapdragon X)·자동차(Ride)로 확장."),
    ("AVGO",  "Broadcom Inc.",             "Technology",             "반도체 — AI 칩 · 설계",    "커스텀 AI ASIC 1위 (~60%)",       "#e60024", 2, "USD",
        "하이퍼스케일러 커스텀 AI ASIC 코디자인 1위 (Google·Meta·OpenAI) + 머천트 스위치 칩(Tomahawk) + VMware 인프라 SW. ASIC 시대의 최대 수혜."),
    ("MRVL",  "Marvell Technology, Inc.",  "Technology",             "반도체 — AI 칩 · 설계",    "커스텀 AI ASIC 2위 (~25%)",       "#de3163", 2, "USD",
        "하이퍼스케일러 커스텀 AI ASIC 코디자인 2위 (Amazon Trainium·Microsoft). 광 DSP·DPU·인터커넥트 실리콘 — Broadcom 과 함께 ASIC 양강."),
    ("2454.TW", "MediaTek Inc.",           "Technology",             "반도체 — AI 칩 · 설계",    "모바일 AP 물량 1위 (~40%)",       "#f7a600", 0, "TWD",
        "스마트폰 AP-SoC 물량 세계 1위 (~40%, Dimensity). 온디바이스 AI 폰의 중저가 확산 축 + Google TPU v8 설계 참여설 등 ASIC 확장."),
    ("MBLY",  "Mobileye Global Inc.",      "Technology",             "반도체 — AI 칩 · 설계",    "카메라 ADAS 칩 ~65%",             "#0b67b2", 2, "USD",
        "카메라 기반 ADAS 칩·SW 점유율 ~65% (Intel 자회사). EyeQ 칩 누적 출하 2억개 — 자율주행 L2+→L4 전환기 차량용 AI 칩의 기준 종목."),
    ("SNPS",  "Synopsys, Inc.",            "Technology",             "반도체 — AI 칩 · 설계",    "EDA (설계 자동화 SW) 1위",        "#5a2d81", 2, "USD",
        "칩 설계 자동화(EDA) 1위 + 설계 IP 2위. Cadence 와 듀오폴리(합산 ~60%) — AI 칩 설계 복잡도 급증의 구조적 관문. 대중 수출통제 지렛대."),
    ("CDNS",  "Cadence Design Systems",    "Technology",             "반도체 — AI 칩 · 설계",    "EDA 2위 (Synopsys 와 양강)",      "#d42e34", 2, "USD",
        "EDA 양강. AI 기반 설계 자동화(Cerebrus)·검증·시뮬레이션 강자 — 커스텀 ASIC 붐과 칩 설계 스타트업 증가의 직접 수혜."),
    ("ARM",   "Arm Holdings plc",          "Technology",             "반도체 — AI 칩 · 설계",    "CPU IP · ISA 사실상 표준",        "#0091bd", 2, "USD",
        "모바일 CPU IP ~99% + 서버·엣지로 확장 중인 ISA 표준. 칩이 팔릴 때마다 로열티를 수취하는 'toll booth' 모델. 소프트뱅크 지배."),

    # ── 반도체 — 메모리 (HBM·DRAM) ───────────────────────────────────
    ("005930.KS", "Samsung Electronics",   "Technology",             "반도체 — 메모리 (HBM·DRAM)", "메모리 1위 + 파운드리 + AP",     "#1428a0", 0, "KRW",
        "DRAM·NAND 세계 1위 종합 반도체. HBM4 Rubin 인증으로 SK 추격 + 파운드리 2nm GAA + 엑시노스 AP — 시장지도의 메모리·파운드리·AP 세 노드에 동시 등장하는 유일 기업."),
    ("000660.KS", "SK Hynix",              "Technology",             "반도체 — 메모리 (HBM·DRAM)", "HBM 세계 1위 (~62%)",            "#ec1c24", 0, "KRW",
        "HBM 점유율 ~62% 세계 1위 — HBM4 를 NVIDIA 에 최초 인증·양산. MR-MUF 적층 공정 수율 우위. AI 메모리 슈퍼사이클의 최대 수혜주. DRAM 2위 + Solidigm NAND."),
    ("MU",    "Micron Technology, Inc.",   "Technology",             "반도체 — 메모리 (HBM·DRAM)", "메모리 3강 · HBM ~21%",          "#00a85b", 2, "USD",
        "메모리(DRAM·NAND) 글로벌 3강. HBM 점유율 ~21%, ’26 물량 완판 — 미국 유일 메모리 제조사로 지정학 수혜."),

    # ── 반도체 — 파운드리 · 패키징 · 기판 ────────────────────────────
    ("TSM",   "Taiwan Semiconductor Mfg.", "Technology",             "반도체 — 파운드리 · 패키징 · 기판", "세계 1위 파운드리 + CoWoS 지배", "#d11919", 2, "USD",
        "세계 1위 반도체 파운드리 (선단 ≤5nm 90%+). 애플·NVIDIA·AMD 핵심 칩을 거의 다 제조 + CoWoS 첨단 패키징 지배 — AI 칩 밸류체인의 단일 관문."),
    ("AMKR",  "Amkor Technology, Inc.",    "Technology",             "반도체 — 파운드리 · 패키징 · 기판", "OSAT 2위 · 美 첨단 패키징 증설", "#e87722", 2, "USD",
        "패키징·테스트 외주(OSAT) 세계 2위. TSMC CoWoS 오버플로 2차 공급 + 애리조나 첨단 패키징 공장 — 미국 내 패키징 리쇼어링의 핵심."),
    ("4062.T", "Ibiden Co., Ltd.",         "Technology",             "반도체 — 파운드리 · 패키징 · 기판", "최고급 ABF 기판 (NVIDIA 향)",    "#1b5faa", 0, "JPY",
        "AI 서버용 최고급 ABF 기판 양강 (NVIDIA 주공급). ’26 고급 ABF 공급부족 전환의 최대 수혜 — 기판이 패키징 다음의 2차 병목."),

    # ── 반도체 — 장비 · 소재 ─────────────────────────────────────────
    ("ASML",  "ASML Holding N.V.",         "Technology",             "반도체 — 장비 · 소재",     "노광장비 (EUV) 글로벌 독점",      "#0091da", 2, "USD",
        "반도체 미세공정의 핵심 노광장비 (EUV/High-NA) 글로벌 100% 독점 (네덜란드). 전 밸류체인에서 구조적으로 가장 단단한 병목. 1대 약 4억 달러."),
    ("AMAT",  "Applied Materials, Inc.",   "Technology",             "반도체 — 장비 · 소재",     "반도체 장비 종합 1위",             "#0095da", 2, "USD",
        "반도체 장비 종합 1위 (식각·증착 등). 메모리·로직 모든 공정에 폭넓게 공급. 반도체 capex 사이클의 거울."),
    ("LRCX",  "Lam Research Corp.",        "Technology",             "반도체 — 장비 · 소재",     "반도체 장비 (식각·증착)",          "#10b981", 2, "USD",
        "반도체 식각·증착 장비 강자. 메모리(DRAM·NAND)·HBM TSV 공정에 특히 강세. 한국 삼성·SK 가 큰 고객."),
    ("TOELY", "Tokyo Electron Limited",    "Technology",             "반도체 — 장비 · 소재",     "일본 1위 장비 (코터 독점)",       "#9e1b32", 2, "USD",
        "일본 1위 반도체 장비. EUV 포토레지스트 코터/디벨로퍼 사실상 독점 + 식각·증착. 글로벌 WFE 4강 (ADR)."),
    ("KLAC",  "KLA Corporation",           "Technology",             "반도체 — 장비 · 소재",     "계측·검사 ~74% 준독점",           "#0067b1", 2, "USD",
        "계측·검사 장비 ~74% 준독점. AI 칩 복잡도·수율 비용 상승의 구조적 수혜 — GAA·HBM 수율 전쟁의 무기상."),
    ("042700.KS", "Hanmi Semiconductor",   "Technology",             "반도체 — 장비 · 소재",     "HBM TC 본더 세계 1위",            "#0aa5c2", 0, "KRW",
        "HBM 적층용 TC 본더 세계 1위 — SK하이닉스·마이크론 공급. 적층 수율(=HBM 병목)의 심장인 본딩 장비를 쥔 국내 최대 수혜 장비주."),
    ("6857.T", "Advantest Corporation",    "Technology",             "반도체 — 장비 · 소재",     "반도체 테스터 세계 1위",          "#e8380d", 0, "JPY",
        "반도체 테스터 세계 1위 (Teradyne 과 양강). HBM 스택 전수 테스트 + AI SoC 테스트 시간 증가가 구조적 순풍."),
    ("6146.T", "DISCO Corporation",        "Technology",             "반도체 — 장비 · 소재",     "그라인더·다이서 독점적 1위",      "#2f7d32", 0, "JPY",
        "웨이퍼를 얇게 갈고(그라인더) 자르는(다이서) 장비 70~80% 독점적 1위. HBM 12·16단 적층의 초박형 다이 가공 필수 — 첨단 패키징의 숨은 관문."),
    ("BESI.AS", "BE Semiconductor Industries", "Technology",         "반도체 — 장비 · 소재",     "하이브리드 본딩 장비 선두",       "#7a3ea8", 2, "EUR",
        "어드밴스드 패키징용 하이브리드 본딩 장비 선두 (Applied Materials 제휴). HBM4E·SoIC 세대의 칩렛 적층 전환 수혜 — 유럽 소형 강자."),
    ("4063.T", "Shin-Etsu Chemical",       "Materials",              "반도체 — 장비 · 소재",     "실리콘 웨이퍼 1위 + 레지스트",    "#b5121b", 0, "JPY",
        "실리콘 웨이퍼 세계 1위 (SUMCO 와 듀오폴리) + 포토레지스트 강자. 소재 노드의 지정학 리스크(일본 >90% 집중)를 대표하는 종목."),

    # ── AI 인프라 — 네트워킹 · 광 · 네오클라우드 ─────────────────────
    ("ANET",  "Arista Networks, Inc.",     "Technology",             "AI 인프라 — 네트워킹 · 광 · 네오클라우드", "AI 이더넷 스위치 1위", "#2a5caa", 2, "USD",
        "데이터센터 이더넷 스위치 1위권 (~19%). AI 백엔드 네트워크의 이더넷 전환(InfiniBand 대체) 최대 수혜 — 하이퍼스케일러가 주고객."),
    ("COHR",  "Coherent Corp.",            "Technology",             "AI 인프라 — 네트워킹 · 광 · 네오클라우드", "광 트랜시버·CPO 수직통합", "#00a870", 2, "USD",
        "800G/1.6T 광 트랜시버 수직통합 강자 + NVIDIA CPO 파트너. GPU 클러스터 확장의 병목이 구리→광으로 이동하는 국면의 수혜."),
    ("MPWR",  "Monolithic Power Systems",  "Technology",             "AI 인프라 — 네트워킹 · 광 · 네오클라우드", "GPU 전력전달 'last inch'", "#0a66a0", 2, "USD",
        "고밀도 전원관리 반도체(PMIC) 강자. GPU 랙 전력밀도 급증(랙 100kW→MW급)의 'last inch' 전력전달 — NVIDIA 전력 체인 핵심."),
    ("CRWV",  "CoreWeave, Inc.",           "Technology",             "AI 인프라 — 네트워킹 · 광 · 네오클라우드", "네오클라우드 1위",       "#6b46c1", 2, "USD",
        "최대 독립 GPU 클라우드 — 계약 잔고 $99B+. NVIDIA 앵커 투자 + MS·OpenAI 대형 계약. GPU 담보 부채의 순환금융 구조가 핵심 리스크."),
    ("NBIS",  "Nebius Group N.V.",         "Technology",             "AI 인프라 — 네트워킹 · 광 · 네오클라우드", "네오클라우드 2위권",     "#00a8a8", 2, "USD",
        "구 Yandex 분할 네오클라우드. Meta $27B·MS 계약으로 잔고 ~$50B, 계약전력 3GW+ — 'GPU 확보전 → 전력 전쟁' 국면의 선두권."),

    # ── 로보틱스 / 피지컬 AI ──────────────────────────────────────────
    ("TER",   "Teradyne, Inc.",            "Technology",             "로보틱스 / 피지컬 AI",     "반도체 테스트 + 협동로봇",        "#e31837", 2, "USD",
        "반도체 자동시험장비(ATE) 양강 + 협동로봇(Universal Robots)·자율이동로봇(MiR). AI 칩 테스트 수요와 피지컬 AI 양쪽에 걸친 이중 노출."),
    ("HSAI",  "Hesai Group",               "Technology",             "로보틱스 / 피지컬 AI",     "라이다 출하 세계 1위",            "#0084ff", 2, "USD",
        "차량 ADAS·로보틱스용 라이다 출하 세계 1위(연 160만개+, 첫 흑자전환). 로봇향 출하 +400%대 폭증 — 휴머노이드·로보택시의 '눈'."),
    ("MP",    "MP Materials Corp.",        "Materials",              "로보틱스 / 피지컬 AI",     "비중국 희토류·자석 수직계열화",   "#b87333", 2, "USD",
        "미국 유일 희토류 채굴(Mountain Pass)→정제→네오디뮴 자석 수직계열화. 美 국방부 지분 투자. 로봇 모터·액추에이터 핵심 소재 NdPr 자석의 비중국 대안."),
    ("6954.T", "FANUC Corporation",        "Industrials",            "로보틱스 / 피지컬 AI",     "산업용 로봇 글로벌 1위권",        "#e0b400", 0, "JPY",
        "산업용 로봇·CNC 글로벌 1위권 (4강 합산 55%+). 공장 자동화의 기준 종목 — 중국 로컬 추월 압박 속 AI 코봇·피지컬 AI 통합이 반전 카드."),
    ("6324.T", "Harmonic Drive Systems",   "Industrials",            "로보틱스 / 피지컬 AI",     "하모닉 감속기 세계 1위",          "#4a7ab5", 0, "JPY",
        "스트레인 웨이브(하모닉) 감속기 세계 1위. 휴머노이드 1대당 감속기·액추에이터 30~40개 — 로봇 구동부품 구조적 병목의 핵심 수혜."),

    # ── 자동차 / 모빌리티 ─────────────────────────────────────────────
    ("TSLA",  "Tesla Inc.",                "Consumer Discretionary", "자동차 / 모빌리티",        "전기차 + 에너지 + 자율주행",      "#cc0000", 2, "USD",
        "전기차 매출 위주. 에너지 저장(Megapack)·자율주행(FSD)·로봇(Optimus) 개발 중. CEO 일론 머스크 영향력 큼."),
    ("TM",    "Toyota Motor Corporation",  "Consumer Discretionary", "자동차 / 모빌리티",        "글로벌 1위 완성차",                "#eb0a1e", 2, "USD",
        "글로벌 판매량 1위 완성차 (일본). 하이브리드(프리우스) 강자. EV 전환은 상대적으로 보수적."),
    ("F",     "Ford Motor Company",        "Consumer Discretionary", "자동차 / 모빌리티",        "미국 빅3 (Ford F-150)",            "#003478", 2, "USD",
        "미국 빅3 완성차. 픽업트럭 F-150 절대 강자. EV(F-150 Lightning, Mustang Mach-E) 와 내연기관 병행."),
    ("GM",    "General Motors Company",    "Consumer Discretionary", "자동차 / 모빌리티",        "미국 빅3 (Chevrolet, Cadillac)",   "#005daa", 2, "USD",
        "미국 빅3 완성차 (Chevrolet·Cadillac·GMC). EV 플랫폼 Ultium 전개. 자율주행 자회사 Cruise."),
    ("STLA",  "Stellantis N.V.",           "Consumer Discretionary", "자동차 / 모빌리티",        "Chrysler·Peugeot·Fiat 통합",      "#1a3a6e", 2, "USD",
        "Chrysler·Peugeot·Fiat·Jeep 등 14 브랜드를 가진 글로벌 4위 자동차 그룹 (2021 합병)."),
    ("HMC",   "Honda Motor Co., Ltd.",     "Consumer Discretionary", "자동차 / 모빌리티",        "Honda — 일본 2위 완성차",         "#cc0000", 2, "USD",
        "일본 2위 완성차. 자동차 + 오토바이 (오토바이는 글로벌 1위). 하이브리드·F1 엔진 기술 강자."),
    ("RIVN",  "Rivian Automotive, Inc.",   "Consumer Discretionary", "자동차 / 모빌리티",        "미국 EV 픽업트럭 스타트업",       "#ffc814", 2, "USD",
        "미국 EV 픽업트럭·SUV 스타트업 (2021 상장). 아마존이 배송 밴 10만대 주문, 폭스바겐과 합작사 설립."),
    ("NIO",   "NIO Inc.",                  "Consumer Discretionary", "자동차 / 모빌리티",        "중국 프리미엄 EV 대표",            "#00a8e1", 2, "USD",
        "중국 프리미엄 EV 대표주 (NIO ES8 등). 배터리 교환(스왑) 스테이션 차별화. 정부 보조 / 가격경쟁 변수."),
    ("005380.KS", "Hyundai Motor Company", "Consumer Discretionary", "자동차 / 모빌리티",        "한국 1위 완성차",                  "#002c5f", 0, "KRW",
        "한국 1위 완성차. EV(아이오닉)·수소차(넥쏘) 동시 추진. 정의선 회장 지휘 하 미국·인도 시장 성장."),
    ("000270.KS", "Kia Corporation",       "Consumer Discretionary", "자동차 / 모빌리티",        "한국 2위 완성차 (현대차그룹)",     "#bb162b", 0, "KRW",
        "한국 2위 완성차 (현대차그룹). EV6·EV9 등 EV 라인업 호평. 디자인 경쟁력 + 미국 시장 점유율 확대."),

    # ── 바이오 / 제약 / 헬스케어 ──────────────────────────────────────
    ("LLY",   "Eli Lilly and Company",     "Healthcare",             "바이오 / 제약 / 헬스케어", "비만 / 당뇨 치료제 글로벌 1위",    "#d52b1e", 2, "USD",
        "비만치료제(GLP-1) 시장 1위. Zepbound·Mounjaro 매출 폭발로 시총 1조 달러 돌파. 알츠하이머·항암제도 보유."),
    ("NVO",   "Novo Nordisk A/S",          "Healthcare",             "바이오 / 제약 / 헬스케어", "비만 / 당뇨 치료제 양대산맥",      "#0066cc", 2, "USD",
        "덴마크 제약사. Ozempic·Wegovy 등 비만/당뇨 치료제로 Eli Lilly 와 양대산맥. 유럽 시총 1위."),
    ("JNJ",   "Johnson & Johnson",         "Healthcare",             "바이오 / 제약 / 헬스케어", "종합 헬스케어 (제약 + 의료기기)", "#d51b25", 2, "USD",
        "세계 최대 종합 헬스케어. 제약 + 의료기기. 60년 연속 배당 증가의 대표 배당귀족(Dividend King)."),
    ("PFE",   "Pfizer Inc.",               "Healthcare",             "바이오 / 제약 / 헬스케어", "글로벌 제약 + COVID 백신",        "#0093d0", 2, "USD",
        "글로벌 메이저 제약사. COVID-19 백신(Comirnaty)·치료제(Paxlovid)로 팬데믹 수혜 후 정상화 중. 항암제·심혈관."),
    ("MRK",   "Merck & Co., Inc.",         "Healthcare",             "바이오 / 제약 / 헬스케어", "항암제 키트루다 글로벌 1위",      "#00857c", 2, "USD",
        "면역항암제 키트루다(Keytruda) 글로벌 매출 1위 의약품 (연 매출 ~$25B). 2028 특허 만료가 핵심 변수."),
    ("ABBV",  "AbbVie Inc.",               "Healthcare",             "바이오 / 제약 / 헬스케어", "면역질환 (휴미라 후속)",          "#071d49", 2, "USD",
        "면역질환 치료제 강자. 휴미라(Humira) 특허 만료 후 Skyrizi·Rinvoq 등 후속 신약으로 성공적 전환."),
    ("AZN",   "AstraZeneca PLC",           "Healthcare",             "바이오 / 제약 / 헬스케어", "영국 제약 메이저 (항암·호흡기)",  "#830051", 2, "USD",
        "영국 메이저 제약사. 항암제·호흡기·심혈관 강세. COVID 백신 개발. 미국 시장 진출 확대."),
    ("UNH",   "UnitedHealth Group",        "Healthcare",             "바이오 / 제약 / 헬스케어", "미국 1위 의료보험 + 헬스케어",   "#4c8cf8", 2, "USD",
        "미국 최대 의료보험사. 보험(UnitedHealthcare) + 의료서비스(Optum) 결합. 미국 의료비 인플레이션의 핵심 종목."),
    ("TMO",   "Thermo Fisher Scientific",  "Healthcare",             "바이오 / 제약 / 헬스케어", "진단·실험 장비 1위",               "#0086c9", 2, "USD",
        "세계 1위 과학 연구 / 진단 장비·시약 공급사. 제약사·연구소·진단검사센터가 모두 고객. M&A 로 성장."),
    ("ABT",   "Abbott Laboratories",       "Healthcare",             "바이오 / 제약 / 헬스케어", "의료기기 + 진단 + 영양식품",      "#0090d0", 2, "USD",
        "의료기기(연속혈당측정기 Freestyle Libre)·진단·영양식품·일반약. JNJ 와 함께 종합 헬스케어 대표."),

    # ── 에너지 / 원자재 ───────────────────────────────────────────────
    ("XOM",   "Exxon Mobil Corporation",   "Energy",                 "에너지 / 원자재",          "세계 최대 민간 석유·가스 메이저", "#cf0a2c", 2, "USD",
        "세계 최대 민간 석유·가스 회사. 상류(탐사·생산)부터 하류(정제·화학)까지 수직통합. 유가·인플레이션 직접 수혜."),
    ("CVX",   "Chevron Corporation",       "Energy",                 "에너지 / 원자재",          "미국 2위 석유 메이저",            "#1e4d93", 2, "USD",
        "미국 2위 석유 메이저. 상·하류 수직통합. 배당귀족(36년 연속 증가). 워런 버핏 대규모 보유."),
    ("COP",   "ConocoPhillips",            "Energy",                 "에너지 / 원자재",          "북미 상류 (탐사·생산) 전문",      "#e51937", 2, "USD",
        "미국 최대 상류(E&P) 전문 회사. 정제 사업 없이 탐사·생산만. 셰일 + 알래스카 + 카타르 LNG."),
    ("SHEL",  "Shell plc",                 "Energy",                 "에너지 / 원자재",          "Shell — 유럽 메이저",             "#fbce07", 2, "USD",
        "영국·네덜란드 본사 유럽 최대 석유 메이저. 천연가스(LNG) 글로벌 1위 거래 회사. 신재생 점진적 전환."),
    ("OXY",   "Occidental Petroleum",      "Energy",                 "에너지 / 원자재",          "셰일 + 버핏 핵심 보유",            "#cc092f", 2, "USD",
        "미국 셰일 오일 강자 (퍼미안 분지). 워런 버핏이 28% 보유. CCUS(탄소 포집) 기술 투자."),
    ("SLB",   "Schlumberger Limited",      "Energy",                 "에너지 / 원자재",          "유전 서비스 글로벌 1위",          "#0080c8", 2, "USD",
        "유전 서비스(시추·물리탐사·완결) 글로벌 1위. 석유·가스 회사가 사업 영위하려면 거치는 'toll booth'."),
    ("FCX",   "Freeport-McMoRan Inc.",     "Materials",              "에너지 / 원자재",          "세계 최대 구리 광산회사",          "#fa9000", 2, "USD",
        "세계 최대 구리 광산회사. 전기차·신재생에너지 확대로 구리 수요가 핵심 모멘텀. 금도 일부 생산."),
    ("NEM",   "Newmont Corporation",       "Materials",              "에너지 / 원자재",          "세계 최대 금광 회사",              "#c8a032", 2, "USD",
        "세계 최대 금광 회사. 인플레이션·달러 약세·중앙은행 금 매입 수요의 직접 수혜. 금 가격에 연동."),
    ("LIN",   "Linde plc",                 "Materials",              "에너지 / 원자재",          "산업용 가스 글로벌 1위",          "#0072c6", 2, "USD",
        "산업용 가스(질소·산소·수소) 글로벌 1위. 반도체·헬스케어·화학 등 제조업의 필수 인프라."),
    ("APD",   "Air Products & Chemicals",  "Materials",              "에너지 / 원자재",          "산업용 가스 + 청정수소 투자",     "#1c98d3", 2, "USD",
        "산업용 가스 글로벌 2위. 수소 경제(청정수소) 적극 투자. 사우디 NEOM 그린수소 프로젝트 참여."),

    # ── 금융 ──────────────────────────────────────────────────────────
    ("JPM",   "JPMorgan Chase & Co.",      "Financial Services",     "금융",                     "미국 1위 은행 (소매+IB+자산운용)", "#5b8def", 2, "USD",
        "미국 1위 은행. 소비자 금융 + 투자은행(JP Morgan) + 자산운용 결합. 금리·경기 사이클의 대표 종목."),
    ("BAC",   "Bank of America Corp.",     "Financial Services",     "금융",                     "미국 2위 은행 (소매 중심)",       "#e31837", 2, "USD",
        "미국 2위 은행. 소매 금융 중심. 워런 버핏 핵심 보유 종목. 금리 상승 수혜 (NIM 확대)."),
    ("WFC",   "Wells Fargo & Company",     "Financial Services",     "금융",                     "미국 4대 은행 (소매·모기지)",     "#d71e2b", 2, "USD",
        "미국 4대 은행. 소매·모기지 중심. 2016 가짜계좌 스캔들 후 자산 상한 규제 받음 → 최근 해제 기대."),
    ("C",     "Citigroup Inc.",            "Financial Services",     "금융",                     "글로벌 진출 미국 은행",           "#005baa", 2, "USD",
        "미국 4대 은행 중 가장 글로벌화된 은행 (100+ 국가). 트랜잭션 뱅킹·기관 사업 강세."),
    ("GS",    "The Goldman Sachs Group",   "Financial Services",     "금융",                     "투자은행 1위 (M&A·트레이딩)",     "#7a89a4", 2, "USD",
        "글로벌 투자은행 1위. M&A 자문·트레이딩·자산운용. IPO·M&A 사이클에 가장 민감한 종목."),
    ("MS",    "Morgan Stanley",            "Financial Services",     "금융",                     "투자은행 2위 + 자산관리",          "#0066b3", 2, "USD",
        "투자은행 2위. ETrade 인수로 wealth management 비중 확대 → 수익 안정성 개선."),
    ("V",     "Visa Inc.",                 "Financial Services",     "금융",                     "글로벌 결제 네트워크 1위",        "#7c8cf5", 2, "USD",
        "글로벌 결제 네트워크 1위. 카드 결제마다 수수료를 가져가는 'toll booth' 비즈니스. 영업이익률 60%대."),
    ("MA",    "Mastercard Incorporated",   "Financial Services",     "금융",                     "글로벌 결제 네트워크 2위",        "#eb001b", 2, "USD",
        "글로벌 결제 네트워크 2위. Visa 와 사실상 양강. 신용·체크·디지털 결제. 크로스보더 결제 성장."),
    ("AXP",   "American Express Company",  "Financial Services",     "금융",                     "고급 신용카드 (Closed-loop)",     "#016fd0", 2, "USD",
        "고급 신용카드 (Centurion·Platinum). 카드망·발행·가맹 통합(Closed-loop). 워런 버핏 핵심 보유."),
    ("BRK-B", "Berkshire Hathaway Inc. (Class B)", "Financial Services", "금융",                  "워런 버핏 지주회사",               "#a3a3a3", 2, "USD",
        "워런 버핏의 지주회사. 보험(Geico) + 철도(BNSF) + 에너지 + 주식 포트폴리오(애플 비중 큼). 배당 없음."),

    # ── 소비재 ────────────────────────────────────────────────────────
    ("WMT",   "Walmart Inc.",              "Consumer Staples",       "소비재",                   "세계 최대 소매 유통",              "#0071ce", 2, "USD",
        "세계 최대 소매 유통. 미국 가구 90%가 매장 10마일 내 거주. e-commerce 로 Amazon 추격, 광고 사업으로 마진 확대."),
    ("COST",  "Costco Wholesale",          "Consumer Staples",       "소비재",                   "회원제 창고형 매장",               "#e31837", 2, "USD",
        "회원제 창고형 매장. 멤버십 수수료가 영업이익의 70%+, 갱신율 90%대로 매우 충성도 높음. 인플레이션 방어 종목."),
    ("KO",    "The Coca-Cola Company",     "Consumer Staples",       "소비재",                   "글로벌 음료 절대강자",             "#f40009", 2, "USD",
        "200여 개국 판매 글로벌 음료 강자. 60년 연속 배당 증가 배당귀족. 워런 버핏 핵심 보유 종목."),
    ("PEP",   "PepsiCo, Inc.",             "Consumer Staples",       "소비재",                   "음료 + 스낵 (Frito-Lay)",          "#004b93", 2, "USD",
        "음료(펩시) + 스낵(Frito-Lay, Lay's, Doritos). 스낵 사업이 음료보다 큼. 배당귀족."),
    ("PG",    "Procter & Gamble Co.",      "Consumer Staples",       "소비재",                   "생활용품 글로벌 1위",              "#003da5", 2, "USD",
        "생활용품 글로벌 1위 (질레트·팬틴·페브리즈·다우니 등 65개+ 브랜드). 65년 연속 배당 증가 배당귀족."),
    ("MO",    "Altria Group, Inc.",        "Consumer Staples",       "소비재",                   "미국 담배 1위 (Marlboro)",        "#005826", 2, "USD",
        "미국 담배 1위 (Marlboro 브랜드). 50+년 연속 배당 증가. 배당수익률 7%대로 인컴주 대표. ESG 관점 호불호."),
    ("MCD",   "McDonald's Corporation",    "Consumer Discretionary", "소비재",                   "글로벌 패스트푸드 1위",            "#ffc72c", 2, "USD",
        "글로벌 패스트푸드 1위. 사실상 부동산 임대업(가맹점에 부지 임대). 배당귀족 47년 연속 증가."),
    ("HD",    "The Home Depot, Inc.",      "Consumer Discretionary", "소비재",                   "미국 1위 홈임프루브먼트",         "#f96302", 2, "USD",
        "미국 1위 홈임프루브먼트 매장 (Lowe's 와 양대). DIY + 프로용. 주택 시장·금리에 민감."),
    ("NKE",   "NIKE, Inc.",                "Consumer Discretionary", "소비재",                   "스포츠웨어 글로벌 1위",            "#fa5400", 2, "USD",
        "스포츠웨어 글로벌 1위. 운동화·의류·용품. D2C 강화 + 중국 시장 회복이 핵심 변수."),
    ("SBUX",  "Starbucks Corporation",     "Consumer Discretionary", "소비재",                   "글로벌 커피 체인 1위",             "#006241", 2, "USD",
        "글로벌 커피 체인 1위. 중국 시장 회복·국내 가격 경쟁이 주가 변수. 모바일 주문·로열티 프로그램 강세."),

    # ── 산업재 / 방산 ─────────────────────────────────────────────────
    ("CAT",   "Caterpillar Inc.",          "Industrials",            "산업재 / 방산",            "세계 1위 건설·광산 장비",          "#ffcd11", 2, "USD",
        "세계 1위 건설·광산 장비 제조. 글로벌 인프라 투자·자원개발 사이클의 대표주. 농업·엔진 사업도 운영."),
    ("DE",    "Deere & Company",           "Industrials",            "산업재 / 방산",            "John Deere — 농기계 1위",         "#367c2b", 2, "USD",
        "John Deere — 농기계 글로벌 1위. 정밀 농업(See & Spray, 자율 트랙터) 기술 선도. 농산물 가격에 동행."),
    ("BA",    "The Boeing Company",        "Industrials",            "산업재 / 방산",            "Airbus 와 함께 민항기 양대 강자", "#5b8df8", 2, "USD",
        "Airbus 와 함께 민항기 양대 강자. 737·787·777 시리즈. 방산(F/A-18, 우주) 도 운영. 최근 품질·안전 이슈."),
    ("LMT",   "Lockheed Martin Corp.",     "Industrials",            "산업재 / 방산",            "미국 1위 방산 (F-35)",            "#86a3d4", 2, "USD",
        "미국 1위 방산기업. F-35 스텔스 전투기·미사일·우주 시스템. 미 국방예산 + NATO·일본·한국 수출 직접 수혜."),
    ("RTX",   "RTX Corporation",           "Industrials",            "산업재 / 방산",            "Raytheon — 미사일·항공엔진",      "#c8102e", 2, "USD",
        "구 Raytheon Technologies. 미사일(Patriot, Tomahawk)·항공엔진(Pratt & Whitney)·국방 시스템. 우크라이나·중동 분쟁 수혜."),
    ("NOC",   "Northrop Grumman Corp.",    "Industrials",            "산업재 / 방산",            "전략핵·우주 시스템 방산",          "#0066a1", 2, "USD",
        "미국 4대 방산. 전략 핵폭격기(B-21 Raider)·핵미사일(Sentinel)·우주(NASA 협력) 강자. 미·중 우주 경쟁 수혜."),
    ("HON",   "Honeywell International",   "Industrials",            "산업재 / 방산",            "산업복합 (항공·자동화)",          "#e1241c", 2, "USD",
        "산업복합 (항공우주·빌딩기술·에너지·자동화·헬스케어). GE·3M 과 함께 미국 산업복합 대표."),
    ("GE",    "GE Aerospace",              "Industrials",            "산업재 / 방산",            "항공기 엔진 (LEAP) 1위",          "#005eb8", 2, "USD",
        "민항기 엔진(LEAP) Safran 합작 통해 글로벌 1위. 2024 GE 분할로 항공우주만 남음. 항공 운항 시간(FH) 연동."),
    ("UPS",   "United Parcel Service",     "Industrials",            "산업재 / 방산",            "글로벌 물류 1위",                  "#351c15", 2, "USD",
        "글로벌 물류·택배 1위 (갈색 트럭). 220개 국가 배송. e-commerce 성장과 동행, B2B 산업 사이클에 민감."),
    ("FDX",   "FedEx Corporation",         "Industrials",            "산업재 / 방산",            "글로벌 익일배송 1위",              "#4d148c", 2, "USD",
        "글로벌 익일·국제 배송 1위 (Express). UPS 와 양대. 보잉 757/767 항공기 다수 보유."),
    ("AVAV",  "AeroVironment, Inc.",       "Industrials",            "산업재 / 방산",            "소모성 드론·배회폭탄 1위",        "#1f6fb2", 2, "USD",
        "Switchblade 배회폭탄·소형 UAS 1위 + BlueHalo 인수로 대드론·레이저·우주 확장. 美 'Drone Dominance' 조달 확대의 직접 수혜 퓨어플레이."),
    ("KTOS",  "Kratos Defense & Security", "Industrials",            "산업재 / 방산",            "저가 무인전투기 (CCA)",           "#5a7d9a", 2, "USD",
        "저가 무인전투기 XQ-58 Valkyrie·표적드론·제트엔진. 해병대 CCA 기체 선정 — '소모 가능한 무인 윙맨' 대량생산 테마의 핵심 상장주."),
    ("012450.KS", "Hanwha Aerospace",      "Industrials",            "산업재 / 방산",            "K-방산 대장주 (K9·유무인복합)",   "#f37321", 0, "KRW",
        "K9 자주포·천무 수출 + 항공엔진. 유럽 재무장 최대 수혜 K-방산 대장주. UGV·유무인복합으로 피지컬 AI 확장."),
    ("079550.KS", "LIG Nex1",              "Industrials",            "산업재 / 방산",            "유도무기·대드론 (천궁)",          "#c4122f", 0, "KRW",
        "천궁-II 등 유도무기 수출 주력. 중형무인기 공통플랫폼·대드론 체계로 무인전 확장. 중동 수출 모멘텀."),

    # ── 부동산 (REITs) ────────────────────────────────────────────────
    ("AMT",   "American Tower Corporation", "Real Estate",           "부동산 (REITs)",           "세계 최대 통신탑 REIT",            "#4ea1ff", 2, "USD",
        "세계 최대 통신탑(셀타워) REIT. 통신사들에 5G 안테나 임대. 디지털 인프라의 'toll bridge' 모델."),
    ("CCI",   "Crown Castle Inc.",         "Real Estate",            "부동산 (REITs)",           "통신탑 REIT 2위",                  "#005faf", 2, "USD",
        "미국 통신탑 REIT 2위. 광케이블(Fiber) 사업 보유. AMT 와 양대. 5G 인프라 임대수익."),
    ("PLD",   "Prologis, Inc.",            "Real Estate",            "부동산 (REITs)",           "세계 최대 물류창고 REIT",          "#34d399", 2, "USD",
        "세계 최대 물류창고 REIT. 아마존 등 e-commerce 성장에 따른 물류센터 임대수익 폭발. AI 데이터센터로 확장."),
    ("EQIX",  "Equinix, Inc.",             "Real Estate",            "부동산 (REITs)",           "글로벌 데이터센터 REIT 1위",      "#f97316", 2, "USD",
        "글로벌 데이터센터 REIT 1위. 70+ 도시에 데이터센터 운영. 클라우드·AI 인프라 폭증의 직접 수혜자."),
    ("DLR",   "Digital Realty Trust",      "Real Estate",            "부동산 (REITs)",           "데이터센터 REIT 2위",              "#0078c2", 2, "USD",
        "글로벌 데이터센터 REIT 2위 (Equinix 와 양대). 하이퍼스케일·엔터프라이즈 데이터센터. AI 학습·추론 수요 수혜."),
    ("O",     "Realty Income Corporation", "Real Estate",            "부동산 (REITs)",           "월 배당 'The Monthly Dividend Company'", "#1a3a6e", 2, "USD",
        "월 단위 배당으로 유명 ('The Monthly Dividend Company'). 미국 단일 임차인 소매(Convenience store 등) 임대."),
    ("SPG",   "Simon Property Group",      "Real Estate",            "부동산 (REITs)",           "미국 최대 쇼핑몰 REIT",            "#a90030", 2, "USD",
        "미국 최대 쇼핑몰 REIT. 프리미엄 아웃렛 + 럭셔리 쇼핑몰. e-commerce 시대에도 프리미엄 입지 가치 유지."),
    ("WELL",  "Welltower Inc.",            "Real Estate",            "부동산 (REITs)",           "시니어 헬스케어 REIT 1위",        "#3aaa35", 2, "USD",
        "시니어 헬스케어 REIT 1위. 요양원·시니어 아파트·메디컬 오피스. 인구 고령화 장기 수혜."),
    ("PSA",   "Public Storage",            "Real Estate",            "부동산 (REITs)",           "셀프 스토리지 REIT 1위",          "#75b73b", 2, "USD",
        "셀프 스토리지(개인 창고 임대) REIT 1위. 미국 전역에 ~3,000개 창고. 운영비 낮고 가격 결정력 강함."),
    ("VICI",  "VICI Properties Inc.",      "Real Estate",            "부동산 (REITs)",           "카지노·엔터테인먼트 REIT",        "#c8102e", 2, "USD",
        "라스베이거스 카지노·엔터테인먼트 부동산 REIT. Caesars Palace·MGM Grand 등 임대. S&P 500 편입."),

    # ── 통신 / 미디어 ────────────────────────────────────────────────
    ("VZ",    "Verizon Communications",    "Communication Services", "통신 / 미디어",            "미국 1위 통신 (5G)",              "#cd040b", 2, "USD",
        "미국 1위 통신사 (무선 기준). 5G 네트워크 + 광케이블. 고배당 (수익률 6%대) 인컴주."),
    ("T",     "AT&T Inc.",                 "Communication Services", "통신 / 미디어",            "미국 2위 통신 + 광케이블",        "#00a8e0", 2, "USD",
        "미국 2위 통신사. WarnerMedia 분사 후 통신 본업 집중. 광케이블 인터넷 확대 중. 고배당."),
    ("TMUS",  "T-Mobile US, Inc.",         "Communication Services", "통신 / 미디어",            "미국 3위 통신 (5G 1위)",          "#e20074", 2, "USD",
        "미국 3위 통신사. Sprint 인수로 5G 인프라 1위. VZ·T 와의 점유율 경쟁의 승자."),
    ("CMCSA", "Comcast Corporation",       "Communication Services", "통신 / 미디어",            "미국 케이블·미디어 (NBCUniversal)", "#1d3a83", 2, "USD",
        "미국 케이블·인터넷 1위 + NBCUniversal(영화·테마파크). 스트리밍(Peacock) 진출. 케이블 가입자 감소가 변수."),
    ("CHTR",  "Charter Communications",    "Communication Services", "통신 / 미디어",            "미국 케이블·인터넷 2위 (Spectrum)", "#0099d8", 2, "USD",
        "미국 케이블·인터넷 2위 (Spectrum 브랜드). Comcast 와 양대. 무선 사업(Spectrum Mobile) 확대 중."),
    ("NFLX",  "Netflix, Inc.",             "Communication Services", "통신 / 미디어",            "글로벌 스트리밍 1위",              "#e50914", 2, "USD",
        "글로벌 스트리밍 1위 (가입자 ~3억). 광고형 요금제 + 계정공유 단속으로 마진 개선. 자체 콘텐츠 강자."),
    ("DIS",   "The Walt Disney Company",   "Communication Services", "통신 / 미디어",            "디즈니 — 종합 미디어·엔터",      "#022a5e", 2, "USD",
        "디즈니 — 종합 미디어·엔터 (영화·테마파크·ESPN·디즈니+). Marvel·Pixar·Star Wars IP 보유."),
    ("SPOT",  "Spotify Technology S.A.",   "Communication Services", "통신 / 미디어",            "글로벌 음악 스트리밍 1위",        "#1db954", 2, "USD",
        "글로벌 음악 스트리밍 1위 (스웨덴). 가입자 6억+. 팟캐스트·오디오북 확장. 음악 레이블에 로열티 지불 구조."),
    ("EA",    "Electronic Arts Inc.",      "Communication Services", "통신 / 미디어",            "글로벌 게임 (FIFA·Apex)",         "#ff4747", 2, "USD",
        "글로벌 게임 퍼블리셔. FC(구 FIFA)·Madden NFL·Apex Legends·심즈. 스포츠 게임 라이선스 강자."),
    ("TTWO",  "Take-Two Interactive",      "Communication Services", "통신 / 미디어",            "GTA·NBA 2K 개발사",                "#e60012", 2, "USD",
        "Grand Theft Auto·NBA 2K 개발사 (Rockstar Games·2K). GTA VI 출시(2025-26) 가 가장 큰 카탈리스트."),

    # ── 유틸리티 / 전력 ──────────────────────────────────────────────
    ("NEE",   "NextEra Energy, Inc.",      "Utilities",              "유틸리티 / 전력",          "미국 1위 신재생 유틸리티",        "#1ab394", 2, "USD",
        "미국 1위 신재생(풍력·태양광) 유틸리티 + 플로리다 전력회사. 신재생 자산 규모 글로벌 최대급."),
    ("SO",    "The Southern Company",      "Utilities",              "유틸리티 / 전력",          "미국 남부 전력 유틸리티",          "#005ba8", 2, "USD",
        "미국 동남부 (조지아·앨라배마 등) 전력 유틸리티. 보글 원전(Vogtle 3·4호기) 가동 — 미국 최신 원전."),
    ("DUK",   "Duke Energy Corporation",   "Utilities",              "유틸리티 / 전력",          "미국 동남부 전력 유틸리티",       "#003366", 2, "USD",
        "미국 동남부 (노스캐롤라이나·플로리다 등) 전력·가스 유틸리티. 원전·가스·신재생 혼합 전원믹스."),
    ("AEP",   "American Electric Power",   "Utilities",              "유틸리티 / 전력",          "미국 송전망 최대 (765kV)",        "#0072ce", 2, "USD",
        "미국 송전망 1위 (765kV 초고압). 11개 주에 발전·송배전. AI 데이터센터 전력 수요 직접 수혜."),
    ("EXC",   "Exelon Corporation",        "Utilities",              "유틸리티 / 전력",          "송배전 전문 (Pure-play T&D)",     "#0085ca", 2, "USD",
        "송배전 전문 유틸리티 (발전 분리). 시카고(ComEd)·필라델피아(PECO)·볼티모어 등 대도시 전력 공급."),
    ("CEG",   "Constellation Energy",      "Utilities",              "유틸리티 / 전력",          "미국 1위 원자력 발전사",          "#a3238e", 2, "USD",
        "미국 1위 원자력 발전사 (~10% 전력 공급). 마이크로소프트와 24년 PPA (스리마일섬 재가동) 체결로 AI 전력 수혜 대표주."),
    ("VST",   "Vistra Corp.",              "Utilities",              "유틸리티 / 전력",          "원자력 + 가스 발전사",            "#003c71", 2, "USD",
        "텍사스 중심 발전사 (원자력 + 가스). 2024 Energy Harbor 인수로 원전 4기 추가. AI 전력 수요 수혜."),
    ("SRE",   "Sempra",                    "Utilities",              "유틸리티 / 전력",          "남부캘리포니아 + LNG 수출",        "#dd0c2f", 2, "USD",
        "남부 캘리포니아 가스·전력 (SoCalGas·SDG&E) + 멕시코 / 미국 LNG 수출 터미널. 에너지·유틸리티 하이브리드."),
    ("ED",    "Consolidated Edison",       "Utilities",              "유틸리티 / 전력",          "뉴욕시 전력·가스 독점",            "#0033a0", 2, "USD",
        "뉴욕시 전력·가스 독점 공급 (1823년 창업). 49년 연속 배당 증가. 가장 안정적인 인컴주 중 하나."),
    ("D",     "Dominion Energy, Inc.",     "Utilities",              "유틸리티 / 전력",          "버지니아 전력 (데이터센터 메카)", "#0066cc", 2, "USD",
        "버지니아·캐롤라이나 전력. 버지니아 북부는 미국 최대 데이터센터 클러스터(~70% 인터넷 트래픽). AI 전력 수혜."),

    # ── 전력 인프라 (AI) ──────────────────────────────────────────────
    ("GEV",   "GE Vernova Inc.",           "Industrials",            "전력 인프라 (AI)",         "가스터빈·그리드 장비 1위",        "#00b5e2", 2, "USD",
        "GE 에서 분사한 발전·그리드 장비사. 대형 가스터빈 글로벌 1위 — 백로그 110GW+ 로 2029년까지 매진. AI 전력 붐의 최상류 공급 관문."),
    ("ETN",   "Eaton Corporation plc",     "Industrials",            "전력 인프라 (AI)",         "북미 전력기기 종합 강자",         "#0033a0", 2, "USD",
        "변압기·스위치기어·UPS 등 전력관리 종합. 데이터센터 인입에서 랙 배전까지 폭넓게 공급 — 변압기 리드타임 4~5년 병목의 핵심 수혜."),
    ("VRT",   "Vertiv Holdings Co",        "Industrials",            "전력 인프라 (AI)",         "DC 전력·냉각 인프라 1위",         "#f7403a", 2, "USD",
        "데이터센터 내부 전력체인(UPS·PDU·부스웨이)과 액체냉각 1위권. NVIDIA GB200/GB300 레퍼런스 파트너 — 랙 전력밀도 급증의 직접 수혜."),
    ("PWR",   "Quanta Services, Inc.",     "Industrials",            "전력 인프라 (AI)",         "송전망 건설 (T&D EPC) 1위",       "#0072ce", 2, "USD",
        "미국 송전·변전 건설(T&D EPC) 1위. 백로그 $48.5B 사상최대 — 유틸리티 grid capex 슈퍼사이클과 DC 대형부하 접속 공사의 최대 수혜."),
    ("BE",    "Bloom Energy Corporation",  "Industrials",            "전력 인프라 (AI)",         "고체산화물 연료전지 (SOFC) 1위",  "#76b900", 2, "USD",
        "천연가스 개질 SOFC 연료전지 1위. 터빈 없이 수개월 내 배치되는 BTM 전원 — Oracle 2.8GW·AEP 1GW·Brookfield $25B 파트너십."),
    ("OKLO",  "Oklo Inc.",                 "Utilities",              "전력 인프라 (AI)",         "SMR (소형모듈원자로) 선두주",     "#a3238e", 2, "USD",
        "Aurora 소형 고속로 개발사 (샘 올트먼 초기 지원). INL 첫 호기 건설 중, Meta 등과 계약 — 데이터센터 전용 24/7 무탄소 전원의 차기 본명."),
    ("034020.KS", "Doosan Enerbility",     "Industrials",            "전력 인프라 (AI)",         "가스터빈·원전 주기기 (한국)",     "#1a5cff", 0, "KRW",
        "국산 가스터빈 + 원전·SMR 주기기 제작. 글로벌 터빈 3사 매진의 반사수혜로 미국향 누적 12기 — 체코 원전 5.6조 수주, SMR 파운드리 전략."),
    ("267260.KS", "HD Hyundai Electric",   "Industrials",            "전력 인프라 (AI)",         "대형 변압기 (북미 수출)",         "#00787d", 0, "KRW",
        "K-전력기기 대장주. 북미 대형 변압기 수출 — ’25 영업이익 1조 돌파, 수년치 수주잔고. 미국 변압기 리드타임 4~5년 병목의 직접 수혜."),
    ("298040.KS", "Hyosung Heavy Industries", "Industrials",         "전력 인프라 (AI)",         "초고압 변압기 (미국 증설)",       "#e60027", 0, "KRW",
        "초고압 변압기·차단기. 미국 현지 공장 증설로 북미 수요 대응 — ’25 영업이익 7,470억 사상최대, 1분기에 연간 수주 목표 절반 달성."),
    ("010120.KS", "LS ELECTRIC",           "Industrials",            "전력 인프라 (AI)",         "배전기기·DC 전력 패키지",         "#c9252c", 0, "KRW",
        "배전기기·전력 시스템. 데이터센터 내부 배전과 Bloom Energy 향 전력 패키지 공급 — 초고압부터 배전반까지 국내 최강 라인업."),

    # ── 조선 (한국) ───────────────────────────────────────────────────
    ("329180.KS", "HD Hyundai Heavy Industries", "Industrials",      "조선 (한국)",             "한국 1위 조선사",                  "#22c55e", 0, "KRW",
        "한국 1위 조선사. 친환경(LNG·암모니아 추진) 선박 분야 글로벌 1위. K-조선 르네상스의 대장주."),
    ("042660.KS", "Hanwha Ocean Co., Ltd.",      "Industrials",      "조선 (한국)",             "방산(잠수함) + 친환경 선박",      "#ec6608", 0, "KRW",
        "구 대우조선해양. 한화그룹 인수 후 방산(잠수함)·친환경 선박으로 사업 확장."),
    ("010140.KS", "Samsung Heavy Industries",     "Industrials",     "조선 (한국)",             "삼성그룹 조선·해양플랜트",        "#1428a0", 0, "KRW",
        "삼성그룹 조선·해양플랜트. LNG 운반선·드릴십·FPSO. 카타르·모잠비크 LNG 메가 프로젝트 참여."),
    ("010620.KS", "HD Hyundai Mipo Dockyard",    "Industrials",      "조선 (한국)",             "중형 선박 (MR 탱커) 전문",        "#0072bc", 0, "KRW",
        "HD현대그룹 중형 조선사. MR(Medium Range) 탱커·PC선·중형 컨테이너선 전문. 친환경 메탄올 추진 선박 강세."),
]

# ============================================================================
# 경쟁사 매핑 (watchlist 내 + 일부 외부 peer)
# ============================================================================
# (각 종목별로 동일 섹터 내 다른 종목들이 기본 peer. + 일부 외부 ticker 보강)
COMPETITORS = {
    # 빅테크 / 소프트웨어
    "AAPL":  ["MSFT", "GOOGL", "AMZN"],
    "MSFT":  ["AAPL", "GOOGL", "AMZN", "ORCL", "CRM"],
    "GOOGL": ["MSFT", "META", "AMZN"],
    "AMZN":  ["MSFT", "GOOGL", "AAPL", "WMT"],
    "META":  ["GOOGL", "SNAP", "PINS"],
    "ORCL":  ["MSFT", "CRM", "SAP", "IBM"],
    "CRM":   ["MSFT", "ORCL", "SAP", "ADBE"],
    "ADBE":  ["MSFT", "CRM"],
    "IBM":   ["MSFT", "ORCL", "ACN"],
    "PLTR":  ["MSFT", "ORCL", "SNOW", "IBM"],
    # 로보틱스 / 피지컬 AI
    "TER":   ["6857.T", "AMAT", "LRCX"],
    "HSAI":  ["2498.HK", "OUST", "MBLY"],
    "MP":    ["LYC.AX", "FCX", "NEM"],
    "6954.T": ["6506.T", "ABBNY", "TER"],
    "6324.T": ["6268.T", "688017.SS", "TER"],
    # 반도체 — AI 칩 · 설계
    "NVDA":  ["AMD", "AVGO", "TSM", "INTC"],
    "AMD":   ["NVDA", "INTC", "AVGO", "TSM"],
    "INTC":  ["AMD", "TSM", "QCOM"],
    "QCOM":  ["2454.TW", "INTC", "AVGO", "MU"],
    "AVGO":  ["MRVL", "NVDA", "AMD", "QCOM"],
    "MRVL":  ["AVGO", "NVDA", "AMD", "ANET"],
    "2454.TW": ["QCOM", "005930.KS", "AAPL"],
    "MBLY":  ["NVDA", "QCOM", "TSLA", "HSAI"],
    "SNPS":  ["CDNS", "ARM"],
    "CDNS":  ["SNPS", "ARM"],
    "ARM":   ["SNPS", "CDNS", "INTC", "AMD"],
    # 반도체 — 메모리 (HBM·DRAM)
    "005930.KS": ["000660.KS", "MU", "TSM", "INTC"],
    "000660.KS": ["005930.KS", "MU"],
    "MU":    ["000660.KS", "005930.KS", "INTC"],
    # 반도체 — 파운드리 · 패키징 · 기판
    "TSM":   ["005930.KS", "INTC", "GFS", "AMKR"],
    "AMKR":  ["ASX", "TSM", "INTC"],
    "4062.T": ["3037.TW", "8046.TW", "AMKR"],
    # 반도체 — 장비 · 소재
    "ASML":  ["AMAT", "LRCX", "KLAC", "TOELY"],
    "AMAT":  ["LRCX", "ASML", "KLAC", "TOELY"],
    "LRCX":  ["AMAT", "ASML", "KLAC", "TOELY"],
    "TOELY": ["AMAT", "LRCX", "ASML", "KLAC"],
    "KLAC":  ["AMAT", "LRCX", "ASML", "TOELY"],
    "042700.KS": ["0522.HK", "BESI.AS", "6857.T"],
    "6857.T": ["TER", "042700.KS"],
    "6146.T": ["0522.HK", "042700.KS", "BESI.AS"],
    "BESI.AS": ["042700.KS", "0522.HK", "AMAT"],
    "4063.T": ["3436.T", "4062.T", "TOELY"],
    # AI 인프라 — 네트워킹 · 광 · 네오클라우드
    "ANET":  ["CSCO", "AVGO", "NVDA", "MRVL"],
    "COHR":  ["LITE", "AVGO", "MRVL"],
    "MPWR":  ["TXN", "ADI", "NVTS"],
    "CRWV":  ["NBIS", "ORCL", "AMZN", "MSFT"],
    "NBIS":  ["CRWV", "ORCL", "IREN"],
    # 자동차 / 모빌리티
    "TSLA":  ["BYDDY", "GM", "F", "RIVN", "NIO"],
    "TM":    ["GM", "F", "HMC", "STLA"],
    "F":     ["GM", "TSLA", "STLA", "TM"],
    "GM":    ["F", "TSLA", "STLA", "TM"],
    "STLA":  ["F", "GM", "TM", "HMC"],
    "HMC":   ["TM", "F", "GM"],
    "RIVN":  ["TSLA", "F", "GM", "NIO"],
    "NIO":   ["TSLA", "RIVN", "LI", "XPEV"],
    "005380.KS": ["000270.KS", "TM", "HMC", "TSLA"],
    "000270.KS": ["005380.KS", "TM", "HMC", "TSLA"],
    # 바이오 / 제약 / 헬스케어
    "LLY":   ["NVO", "JNJ", "MRK", "PFE"],
    "NVO":   ["LLY", "JNJ", "MRK", "SNY"],
    "JNJ":   ["LLY", "PFE", "MRK", "ABBV"],
    "PFE":   ["JNJ", "MRK", "ABBV", "AZN"],
    "MRK":   ["JNJ", "PFE", "BMY", "AZN"],
    "ABBV":  ["JNJ", "MRK", "BMY", "PFE"],
    "AZN":   ["PFE", "MRK", "GSK", "ABBV"],
    "UNH":   ["JNJ", "ELV", "CI", "HUM"],
    "TMO":   ["DHR", "ABT", "ILMN"],
    "ABT":   ["JNJ", "TMO", "MDT", "BSX"],
    # 에너지 / 원자재
    "XOM":   ["CVX", "SHEL", "BP", "COP"],
    "CVX":   ["XOM", "SHEL", "COP", "OXY"],
    "COP":   ["XOM", "CVX", "OXY", "EOG"],
    "SHEL":  ["XOM", "CVX", "BP", "TTE"],
    "OXY":   ["COP", "EOG", "XOM", "CVX"],
    "SLB":   ["HAL", "BKR"],
    "FCX":   ["BHP", "RIO", "NEM", "SCCO"],
    "NEM":   ["GOLD", "FCX", "AEM", "WPM"],
    "LIN":   ["APD", "AIR.PA"],
    "APD":   ["LIN"],
    # 금융
    "JPM":   ["BAC", "WFC", "C", "GS"],
    "BAC":   ["JPM", "WFC", "C"],
    "WFC":   ["JPM", "BAC", "C", "USB"],
    "C":     ["JPM", "BAC", "WFC", "GS"],
    "GS":    ["MS", "JPM", "C"],
    "MS":    ["GS", "JPM", "BLK"],
    "V":     ["MA", "AXP", "PYPL"],
    "MA":    ["V", "AXP", "PYPL"],
    "AXP":   ["V", "MA", "DFS", "COF"],
    "BRK-B": ["JPM", "BAC", "V", "AAPL"],
    # 소비재
    "WMT":   ["COST", "AMZN", "TGT", "KR"],
    "COST":  ["WMT", "TGT", "BJ", "KR"],
    "KO":    ["PEP", "MNST", "KDP"],
    "PEP":   ["KO", "MDLZ", "KDP"],
    "PG":    ["CL", "KMB", "UL", "CHD"],
    "MO":    ["PM", "BTI"],
    "MCD":   ["SBUX", "YUM", "CMG", "QSR"],
    "HD":    ["LOW"],
    "NKE":   ["LULU", "ADDYY", "UAA"],
    "SBUX":  ["MCD", "DPZ", "YUM"],
    # 산업재 / 방산
    "CAT":   ["DE", "CNH", "KMTUY"],
    "DE":    ["CAT", "CNH", "AGCO"],
    "BA":    ["EADSY", "LMT", "RTX", "NOC"],
    "LMT":   ["RTX", "NOC", "GD", "BA"],
    "RTX":   ["LMT", "NOC", "GD", "BA"],
    "NOC":   ["LMT", "RTX", "GD", "BA"],
    "HON":   ["GE", "RTX", "MMM"],
    "GE":    ["RTX", "HON", "BA"],
    "UPS":   ["FDX", "AMZN"],
    "FDX":   ["UPS", "AMZN"],
    "AVAV":  ["KTOS", "LMT", "NOC"],
    "KTOS":  ["AVAV", "NOC", "GE"],
    "012450.KS": ["079550.KS", "042660.KS", "LMT"],
    "079550.KS": ["012450.KS", "LMT", "RTX"],
    # 부동산 (REITs)
    "AMT":   ["CCI", "SBAC", "EQIX", "DLR"],
    "CCI":   ["AMT", "SBAC", "DLR"],
    "PLD":   ["EXR", "PSA", "EGP", "FR"],
    "EQIX":  ["DLR", "AMT", "IRM"],
    "DLR":   ["EQIX", "AMT", "IRM"],
    "O":     ["NNN", "STAG", "WPC"],
    "SPG":   ["MAC", "BPYU", "TCO"],
    "WELL":  ["VTR", "PEAK", "OHI"],
    "PSA":   ["EXR", "CUBE", "LSI"],
    "VICI":  ["GLPI", "MGM", "CZR"],
    # 통신 / 미디어
    "VZ":    ["T", "TMUS"],
    "T":     ["VZ", "TMUS"],
    "TMUS":  ["VZ", "T"],
    "CMCSA": ["CHTR", "DIS", "NFLX"],
    "CHTR":  ["CMCSA", "VZ", "T"],
    "NFLX":  ["DIS", "AMZN", "SPOT", "PARA", "WBD"],
    "DIS":   ["NFLX", "CMCSA", "WBD", "PARA"],
    "SPOT":  ["NFLX", "AAPL"],
    "EA":    ["TTWO", "ATVI", "MSFT"],
    "TTWO":  ["EA", "ATVI", "MSFT"],
    # 유틸리티 / 전력
    "NEE":   ["DUK", "SO", "AEP"],
    "SO":    ["DUK", "AEP", "NEE"],
    "DUK":   ["NEE", "SO", "AEP"],
    "AEP":   ["DUK", "SO", "NEE", "EXC"],
    "EXC":   ["AEP", "ED", "SO"],
    "CEG":   ["VST", "NEE", "DUK"],
    "VST":   ["CEG", "NRG", "NEE"],
    "SRE":   ["AEP", "DUK", "NEE"],
    "ED":    ["EXC", "AEP", "DUK"],
    "D":     ["DUK", "NEE", "SO", "AEP"],
    # 전력 인프라 (AI)
    "GEV":   ["ETN", "034020.KS", "PWR"],
    "ETN":   ["GEV", "VRT", "267260.KS", "298040.KS"],
    "VRT":   ["ETN", "GEV", "010120.KS"],
    "PWR":   ["MTZ", "EME", "GEV", "ETN"],
    "BE":    ["FCEL", "PLUG", "GEV"],
    "OKLO":  ["SMR", "BWXT", "CEG", "034020.KS"],
    "034020.KS": ["GEV", "OKLO", "298040.KS"],
    "267260.KS": ["298040.KS", "010120.KS", "ETN"],
    "298040.KS": ["267260.KS", "010120.KS", "ETN"],
    "010120.KS": ["267260.KS", "298040.KS", "VRT"],
    # 조선 (한국)
    "329180.KS": ["042660.KS", "010140.KS", "010620.KS"],
    "042660.KS": ["329180.KS", "010140.KS", "010620.KS"],
    "010140.KS": ["329180.KS", "042660.KS", "010620.KS"],
    "010620.KS": ["329180.KS", "042660.KS", "010140.KS"],
}

# ============================================================================
# 요일별 섹터 라운드로빈 — 루틴이 daily 실행시 해당 요일의 섹터만 처리
# (월=Monday=0, ..., 일=Sunday=6)
# ============================================================================
DAY_OF_WEEK_SECTORS = {
    0: ["빅테크 / 소프트웨어",
        "AI 인프라 — 네트워킹 · 광 · 네오클라우드"],                  # 월: 빅테크 + AI 인프라 (하이퍼스케일러·네오클라우드 자본 엔진)
    1: ["반도체 — AI 칩 · 설계",
        "반도체 — 메모리 (HBM·DRAM)",
        "반도체 — 파운드리 · 패키징 · 기판",
        "반도체 — 장비 · 소재"],                                       # 화: 반도체 밸류체인 전체 (시장지도와 동기화)
    2: ["로보틱스 / 피지컬 AI", "자동차 / 모빌리티", "조선 (한국)"],  # 수: 피지컬 AI + 모빌리티 + 조선
    3: ["바이오 / 제약 / 헬스케어"],                                   # 목: 바이오
    4: ["에너지 / 원자재", "유틸리티 / 전력", "전력 인프라 (AI)"],    # 금: 실물자산 + 유틸리티 + 전력 인프라
    5: ["금융", "부동산 (REITs)"],                                     # 토: 자본시장
    6: ["소비재", "산업재 / 방산", "통신 / 미디어"],                  # 일: 디펜시브 + 미디어
}
